### ISSUE TITLE
Some feedback from our games

### ISSUE THREAD

**Issue by Frotty** [Cokemonkey11/embargo-td#1] opened 2018-11-19 11:10 UTC
- [x] Perhaps sort units by gold. I didn't use the villager at first because it was on the bottom with the high gold units.
- [x] The spawn animation should just be the ship travelling, maybe with arrows. The magenta effect looks strange.
- [x] Hard to judge gaps between units, maybe a visual indicator would help
- [x] The "shallow water boat" mechanic doesn't really seem utilized well. What is the difference to having this on land? The embargo theme?
- [x] Mobs attacked the archers even when there was a path, due to mobs blocking each other I believe
- [x] The island with trees are unused? Perhaps add some gather/base build mechanic
- [x] Unless you order "hold position" the archers will just move away from their positions
- [x] It reminded me a bit of legion TD, but the great thing there, strategic formations and positions, don't apply here

**Comment by Cokemonkey11** [comment] 2018-11-20 07:40
Thanks!

**Comment by Cokemonkey11** [comment] 2018-11-20 08:37
> The "shallow water boat" mechanic doesn't really seem utilized well. What is the difference to having this on land? The embargo theme?

It's mainly just for the theme, and to be different - which aren't very good reasons.

It adds another dimension to mazing (you must maze against yourself), and it means creeps are affected by mazes slightly differently (float movement type is not slowed down as much by turning)

But overall I think it just makes the game worse. I will keep it for now, but may eventually have to change it.

**Comment by Cokemonkey11** [comment] 2018-11-20 08:39
> Mobs attacked the archers even when there was a path, due to mobs blocking each other I believe

Yes, I am trying to improve this. I reduced their collision size down to `1` but I think the problem isn't solved.

I also increased the between-round duration, so the mobs should be crossing over one another less. We'll see if it's actually an improvement.

Overall though I think you have to leave more space, basically.

**Comment by Cokemonkey11** [comment] 2018-11-20 08:43
> The island with trees are unused? Perhaps add some gather/base build mechanic

I will keep this in mind, but I don't have any ideas of things to add that improve gameplay or reduce time spent waiting. Do you have any ideas?

Basically, I would prefer to do nothing until I have a great idea.

A "coin gathering" mechanic like in fdef could be ineresting.

**Comment by Cokemonkey11** [comment] 2018-11-20 08:43
> Unless you order "hold position" the archers will just move away from their positions

Of course. I think it could be reasonable to automatically hold position each time a unit stops, but it might do more harm than good. What do you think?

I might try this.

Edit: I had a play with this and didn't manage to detect whenever a unit has the `stop` order without polling. Let me know if you have a solution, but for now I don't think the polling cost is worth it

**Comment by Cokemonkey11** [comment] 2018-11-20 09:04
> It reminded me a bit of legion TD, but the great thing there, strategic formations and positions, don't apply here

Not sure I understand the comparison. Embargo is a mazing TD?

**Comment by Cokemonkey11** [comment] 2018-11-20 09:19
Addressed in https://github.com/Cokemonkey11/embargo-td/commit/46459c6ba376aecba2bca2da09a4b7862c785a91

**Closed as completed by Cokemonkey11** 2018-11-20 09:19 UTC
